#!/bin/bash
# NEXTFLOW TASK: multiqc
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}


nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local ts=$(date +%s%3N);
    if [[ ${#ts} == 10 ]]; then echo ${ts}000
    elif [[ $ts == *%3N ]]; then echo ${ts/\%3N/000}
    elif [[ $ts == *3N ]]; then echo ${ts/3N/000}
    elif [[ ${#ts} == 13 ]]; then echo $ts
    else echo "Unexpected timestamp value: $ts"; exit 1
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    mkdir -p "$base"
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  rsync -rRl $1 $2
}

on_exit() {
    exit_status=${nxf_main_ret:=$?}
    printf $exit_status > /home/user/work/foss_23_rep_tut/nf_foss_tut/work/7f/08f455f74ec0b1104cd221f7c512ee/.exitcode
    set +u
    [[ "$tee1" ]] && kill $tee1 2>/dev/null
    [[ "$tee2" ]] && kill $tee2 2>/dev/null
    [[ "$ctmp" ]] && rm -rf $ctmp || true
    exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

nxf_launch() {
    /bin/bash -ue /home/user/work/foss_23_rep_tut/nf_foss_tut/work/7f/08f455f74ec0b1104cd221f7c512ee/.command.sh
}

nxf_stage() {
    true
    # stage input files
    rm -f lung
    rm -f liver
    rm -f gut
    rm -f fastqc_gut_logs
    rm -f fastqc_lung_logs
    rm -f fastqc_liver_logs
    ln -s /home/user/work/foss_23_rep_tut/nf_foss_tut/work/13/95575eb4c9b52d875f5a91e572d496/lung lung
    ln -s /home/user/work/foss_23_rep_tut/nf_foss_tut/work/bf/03b29ffc15b32f4c429cf713701283/liver liver
    ln -s /home/user/work/foss_23_rep_tut/nf_foss_tut/work/e9/6ce431cbc2871e6b3e96b104c8cd64/gut gut
    ln -s /home/user/work/foss_23_rep_tut/nf_foss_tut/work/8c/2235d8b2119a19c057198471bf6712/fastqc_gut_logs fastqc_gut_logs
    ln -s /home/user/work/foss_23_rep_tut/nf_foss_tut/work/07/80f170cb6c75679d44f64751815e70/fastqc_lung_logs fastqc_lung_logs
    ln -s /home/user/work/foss_23_rep_tut/nf_foss_tut/work/6f/d4ce1660fe98f3a85e7ff480cb0e4d/fastqc_liver_logs fastqc_liver_logs
}

nxf_unstage() {
    true
    [[ ${nxf_main_ret:=0} != 0 ]] && return
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /home/user/work/foss_23_rep_tut/nf_foss_tut/work/7f/08f455f74ec0b1104cd221f7c512ee/.command.begin
    set +u
    set -u
    [[ $NXF_SCRATCH ]] && cd $NXF_SCRATCH
    nxf_stage

    set +e
    ctmp=$(set +u; nxf_mktemp /dev/shm 2>/dev/null || nxf_mktemp $TMPDIR)
    local cout=$ctmp/.command.out; mkfifo $cout
    local cerr=$ctmp/.command.err; mkfifo $cerr
    tee .command.out < $cout &
    tee1=$!
    tee .command.err < $cerr >&2 &
    tee2=$!
    ( nxf_launch ) >$cout 2>$cerr &
    pid=$!
    wait $pid || nxf_main_ret=$?
    wait $tee1 $tee2
    nxf_unstage
}

$NXF_ENTRY
